---
# tasks file for postgres

- name: Create superset system user
  shell: useradd -m -r -s /bin/bash superset
  register: create_superset_user
  failed_when:
    - (create_superset_user.rc != 0)
    - ("already exists" not in create_superset_user.stderr)

- name: Set airflow user password
  shell: echo "{{ superset_sys_user }}:{{ superset_sys_password }}" | chpasswd

- name: Create virtualenv
  become: true
  become_method: su
  become_user: "{{ superset_sys_user }}"
  shell: "python3 -m  venv /home/{{ superset_sys_user }}/venv"

- name: Activate virtualenv
  become: true
  become_method: su
  become_user: "{{ superset_sys_user }}"
  shell: . /home/{{ superset_sys_user }}/venv/bin/activate

- name: Upgrade virtualenv pip
  become: true
  become_method: su
  become_user: "{{ superset_sys_user }}"
  shell: /home/{{ superset_sys_user }}/venv/bin/python3 -m pip install --upgrade pip

  ignore_errors: true
- name: Install sqlalchemy
  shell: "/home/{{ superset_sys_user }}/venv/bin/python3 -m pip install sqlalchemy==1.3.24"

- name: Install dataclasses
  shell: "/home/{{ superset_sys_user }}/venv/bin/python3 -m pip  install  dataclasses"


- name: Install superset
  become: true
  become_method: su
  become_user: "{{ superset_sys_user }}"
  shell: /home/{{ superset_sys_user }}/venv/bin/python3 -m  pip install apache-superset

- name: Initialize superset database
  become: true
  become_method: su
  become_user: "{{ superset_sys_user }}"
  shell: . ~/venv/bin/activate && superset db upgrade

- name: Create admin user
  become: true
  become_method: su
  become_user: "{{ superset_sys_user }}"
  shell: |
    export FLASK_APP=superset
    . ~/venv/bin/activate && superset fab create-admin \
    --username {{ superset_admin_username }} \
    --firstname {{ superset_admin_firstname }} \
    --lastname {{ superset_admin_lastname }} \
    --password {{ superset_admin_password }} \
    --email {{ superset_admin_email }}

- name: Load exemples
  become: true
  become_method: su
  become_user: "{{ superset_sys_user }}"
  shell: . ~/venv/bin/activate && superset load_examples
  retries: 5
  ignore_errors: true

  when: superset_load_examples == True


- name: Create default roles and permissions
  become: true
  become_method: su
  become_user: "{{ superset_sys_user }}"
  shell: . ~/venv/bin/activate && superset init

- name: Copy daemon file
  template:
    src: superset-server.service.j2
    dest: /etc/systemd/system/superset-server.service
    owner: "{{ superset_sys_user }}"

- name: Reload daemon
  shell: systemctl daemon-reload

- name: Enable and start superset
  shell: systemctl enable superset-server

- name: Start superset
  shell: systemctl start superset-server


- name: Open superset webserver port
  shell: firewall-cmd --zone=public --add-port={{ superset_port }}/tcp --permanent
  ignore_errors: true

- name: Reload firewall
  shell: firewall-cmd --reload
  ignore_errors: true


- name: Check superset service status
  shell: systemctl status superset-server

