# This is a basic workflow to help you get started with Actions

name: Ansible Install Airflow CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master,dev ]
  pull_request:
    branches: [ master,dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Check Ansible CentOS centos7
        # You may pin to the exact commit or the version.
        # uses: roles-ansible/check-ansible-centos-centos7-action@6abd53bd6911e1ee4cc183c20ffecd34e3463078
        uses: roles-ansible/check-ansible-centos-centos7-action@0.5.0
        with:
          # Paths to the ansible role or playbook you want to be tested.
          targets: "./envs/dev/ansible/install_airflow.yml"

